apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    service: &name order
spec:
  selector:
    service: *name
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name order
  labels:
    service: *name
spec:
  replicas: 3
  selector:
    matchLabels:
      service: *name
  template:
    metadata:
      labels:
        service: *name
    spec:
      containers:
      - name: *name
        image: *name
        env:
          - name: APPLICATION_PORT
            value: "50051"
          - name: ENV
            value: "prod"
          - name: DATA_SOURCE_URL
            value: "root:s3cr3t@tcp(mysql:3306)/orders?charset=utf8mb4&parseTime=True&loc=Local"
          - name: PAYMENT_SERVICE_URL
            value: "xds:///payment-listener"
          - name: SHIPPING_SERVICE_URL
            value: "xds:///shipping-listener"
          - name: MONGO_ADDRESS
            value: '["mongo.default.svc.cluster.local:27017"]'
          - name: MONGO_INITDB_ROOT_USERNAME
            value: adminuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password123

        ports:
          - containerPort: 50051
        volumeMounts:
          - mountPath: /var/run/config
            name: client-config
      volumes:
        - name: client-config
          configMap:
            name: order-client-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: &name order
spec:
  rules:
    - http:
        paths:
          - path: /Order
            pathType: Prefix
            backend:
              service:
                name: *name
                port:
                  number: 50051
  tls:
    - hosts:
        - ingress.local
      secretName: order-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-client-config
data:
  xds_bootstrap.json: |
    {
      "xds_servers": [
        {
          "server_uri": "xds-server.default.svc.cluster.local:18000",  
          "channel_creds": [
            {
              "type": "insecure"
            }
          ]
        }
        
      ],
      
      "node": {
        "id": "25386353-c3e2-42f5-ad65-2b003c3386f5",
        "metadata": {
          "TEST_PROJECT_ID": "We45523"
        },
        "locality": {
          "zone": "my-zone"
        }
      }
    }
