apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: microservices
build:
  artifacts:
  - image: order
    context: order
    docker:
      dockerfile: Dockerfile
  - image: payment
    context: payment
    docker:
      dockerfile: Dockerfile
  - image: shipping
    context: shipping
    docker:
      dockerfile: Dockerfile
  - image: xds-server
    context: xds-server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: default
    manifests:
    - kubernetes-mongodb
    - xds-server/deployment.yaml
    - order/deployment.yaml
    - payment/deployment.yaml
    - shipping/deployment.yaml
