apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    service: &name shipping
spec:
  clusterIP: None
  selector:
    service: *name
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name shipping
  labels:
    service: *name
spec:
  replicas: 3
  selector:
    matchLabels:
      service: *name
  template:
    metadata:
      labels:
        service: *name
    spec:
      containers:
      - name: *name
        image: *name
        env:
          - name: APPLICATION_PORT
            value : "50051"
          - name: ENV
            value: "prod"
          - name: MONGO_ADDRESS
            value:  '["mongo.default.svc.cluster.local:27017"]'
          - name: MONGO_INITDB_ROOT_USERNAME
            value: adminuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: shipping
spec:
  rules:
    - http:
        paths:
          - path: /Shipping
            pathType: Prefix
            backend:
              service:
                name: shipping
                port:
                  number: 50051
  tls:
    - hosts:
        - ingress.local
